#!/usr/bin/env python3
'''
Convert a txt file generated by sfipick to asc format accepted by sfdd
======================================================================
'''

import os, sys, traceback

if os.isatty(sys.stdin.fileno()) or len(sys.argv) < 2:
    helpmsg='''
    'pick.txt' is a file generated by sfipick program
    'outfilename' is the name of the ascii output file
    'column' is the number of the column selected from 'pick.txt' [0,1,...,n]"\n'''
    sys.stderr.write(__doc__+"\n\n")
    sys.stderr.write('Usage: %s < pick.txt outfilename column > outfilename.asc\n\n' % sys.argv[0])
    sys.stderr.write(helpmsg)
    sys.exit(2)

try:
    outfilename = sys.argv[1]
    col = int(sys.argv[2])
    nlines = 0

    for line in sys.stdin:
        print(line.rstrip().split()[col])
        nlines+=1

    print("n1=%d d1=1 o1=0 data_format=ascii_float in=%s" % (nlines,outfilename))
except:
    helmsg='''
    Conversion error. Please check usage and if you are following these rules:
    - The file with the traveltime picks exists and the path is correct in stdin
    - The 'column' parameter is an integer in the columns interval of the file\n'''
    sys.stderr.write(helmsg)
    print(traceback.format_exc())
    sys.exit(2)
