#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# SConstruct (Python3)
# 
# Purpose: Full velocity inversion with NIP tomography.
# Velocity model with plane interfaces.
# 
# Site: https://dirack.github.io
# 
# Version 1.0
# 
# Programmer: Rodolfo A C Neves (Dirack) 31/01/2022
# 
# Email: rodolfo_profissional@hotmail.com
# 
# License: GPL-3.0 <https://www.gnu.org/licenses/gpl-3.0.txt>.

# Madagascar Package
from rsf.proj import *

# Madagascar Recipes
from rsf.recipes.pefInterpolation import pefInterpolation as pef
from rsf.recipes.kimodel import multiLayerModel as mlmod
from rsf.recipes.kimodel import kirchhoffNewtonModeling as kinewmod
from rsf.recipes.kimodel import arr2str

# Main Files
trueModel='trueModel'
stackedSection='stackedSection'
parametersCube='parametersCube'
interpolatedDataCube='interpolatedDataCube'

# Original velocity model
xmax = 6.0 
zmax = 4.0 

layers = ((1.00,1.00,1.00,1.00),
          (1.45,1.45,1.45,1.45),
          (1.85,1.85,1.85,1.85))

velocities = (1.508,
              1.690,
              1.750,
              2.0)

### Modeling ###

# Generate multi layer model
mlmod(interfaces='interfaces',
        dipsfile='interfacesDip',
        modelfile=trueModel,
        xmax=xmax,
        zmax=zmax,
        layers=layers,
        velocities=velocities)

# plot the original velocity model
Result(trueModel,
	'''
	grey color=j scalebar=y label1=Depth unit1=km
	label2=Position unit2=km barlabel=Velocity barunit=km/s
	barreverse=y title="Velocity Model - Plane Interfaces" allpos=yi bias=1.0
	''')

# VFSA Parameters
v0 = float(ARGUMENTS.get('v0',1.5))
ot0 = float(ARGUMENTS.get('ot0',1.0))
dt0 = float(ARGUMENTS.get('dt0',0.008))
nt0 = int(ARGUMENTS.get('nt0',251))
om0 = float(ARGUMENTS.get('om0',1.5))
dm0 = float(ARGUMENTS.get('dm0',0.025))
nm0 = int(ARGUMENTS.get('nm0',121))
aperture = int(ARGUMENTS.get('aperture',30))
cds = bool(ARGUMENTS.get('cds',False))

### velocity inversion using NIP tomography ###

ni = int(ARGUMENTS.get('ni',1)) # Number of iterations in inversion loop
nit = int(ARGUMENTS.get('nit',100)) # Number of iterations in tomography
nitf = int(ARGUMENTS.get('nitf',2)) # Number of interfaces
model = 'model_0' # Constant velocity model

# Traveltime picking
Flow('pick1.txt',stackedSection,'ipick')
Flow('pick2.txt',stackedSection,'ipick')
Flow('pick3.txt',stackedSection,'ipick')
Flow('pick.txt','pick1.txt pick2.txt pick3.txt','/usr/bin/cat $SOURCES')

files=['t0s','m0s']
i=1
for f in files:
	Flow(f+'.asc','pick.txt',
	'''
	./ascFormat.sh ${TARGETS} %d
	'''%i)

	Flow(f,f+'.asc','dd type=float form=native | put n2=1 d2=1 o2=0')
	i=i+1

files=['rns','rnips','betas']
i=0
for f in files:
	Flow(f,[parametersCube,'t0s','m0s'],
	'''
	window n3=1 f3=%d |
	getparameter t0s=${SOURCES[1]} m0s=${SOURCES[2]}
	''' %i)
	i=i+1

# Constant velocity model for stereoniptomo
Flow(model,None,
     '''
     spike n1=301 d1=0.01 o1=0 n2=1001 d2=0.01 o2=-2 mag=1.508 |
     put label1=Depth unit1=km label2=Position unit2=km
     ''' )

# Plot the constant velocity model
Plot(model,model,'grey color=j scalebar=y label1=Depth unit1=km label2=Position unit2=km barlabel=Velocity barunit=km/s barreverse=y title="Constant Velocity Model" allpos=y')

# Generate shotsfile and anglefile for NIP sources
Flow('s2','m0s','spike mag=0')

Flow('shotsfile',['s2','m0s'],'rcat ${SOURCES[1]} axis=2 | transp')

Flow('anglefile',[parametersCube,'t0s','m0s'],
	'''
	window n3=1 f3=2 |
	getparameter t0s=${SOURCES[1]} m0s=${SOURCES[2]} beta=y
	''')

# First iteration to get the velocity gradient in z
nipsources = 'nipsources_1'
nipangles = 'nipangles_1'
ray =  'ray_1'
nipsources = 'nipsources_1'
angles = 'angles_1'

# NIP model setup, ray-tracing from acquisition surface to NIP sources
Flow([ray,nipangles],[model,'shotsfile','anglefile','t0s'],
	'''
	nipmodsetup shotsfile=${SOURCES[1]} anglefile=${SOURCES[2]} t0s=${SOURCES[3]} nipangles=${TARGETS[1]}
	''')

# Rotate ray angles in NIP sources positions in 180 degrees
Flow(angles,nipangles,'math output="input" | put d1=1 o1=1')
Flow(nipsources,ray,'dd type=float')

for i in range(1):

	velinv = 'modelgz_%d' % i
	gz = 'gz_%d' % i
	Flow([velinv,gz],
		[model,nipsources,angles,'t0s','m0s','rnips','betas'],
		'''
		zgradtomo shotsfile=${SOURCES[1]} anglefile=${SOURCES[2]} t0s=${SOURCES[3]} m0s=${SOURCES[4]} rnips=${SOURCES[5]} betas=${SOURCES[6]} gz=${TARGETS[1]} v0=1.508 nit=%d c0=0.1 temp0=5
		''')

	model = velinv

# NIP model setup before velocity model inversion,
# ray-tracing from acquisition surface to NIP sources
Flow(['raygz','nipanglesgz'],[velinv,'shotsfile','anglefile','t0s'],
        '''
        nipmodsetup shotsfile=${SOURCES[1]} anglefile=${SOURCES[2]} t0s=${SOURCES[3]} nipangles=${TARGETS[1]} | dd type=complex
        ''')

Flow('resultgz','raygz','dd type=float')

# Plot inverted velocity model with NIP sources
Plot('velocityModelgz',velinv,
	'''
	grey color=j scalebar=y barreverse=y bias=1.508 title="Inverted velocity model" barlabel="Velocity" barunit="Km/s" min2=1 max2=5
	''')

Plot('inverted-nipsourcesgz','raygz','sfgraph scalebar=y symbol=+ transp=y yreverse=y max1=3 min1=0 min2=1 max2=5 wanttitle=n wantaxis=n plotcol=7 symbolsz=10')

Plot('inverted-interfacesgz',['velocityModelgz','inverted-nipsourcesgz'],'Overlay')

# Plot original velocity model
Plot('mod1gz',trueModel,
	'''
	put label1=Depth unit1=Km label2=Position unit2=Km |
	grey color=j scalebar=y barreverse=y bias=1.508 title="Original velocity model" barlabel="Velocity" barunit="Km/s" min1=0 max1=3 min2=1 max2=5
	''')

Plot('mod1-imggz',['mod1gz','inverted-nipsourcesgz'],'Overlay')

# Plot result: Inverted and original models side by side
Result('invertedgz',['inverted-interfacesgz','mod1-imggz'],'SideBySideIso')

sv='sv_2'

Flow('sv_2.asc',None,
	'''
	echo 1.508 1.5 1.5 1.5 1.5 2.0 n1=6 data_format=ascii_float in=${TARGETS[0]}
	''')

# Layer's velocity
Flow(sv,'sv_2.asc',
	'''
	dd type=float form=native
	''')

Flow('constv',None,'math output="1.5" n1=301 n2=1001 d1=0.01 d2=0.01 o2=-2 o1=0')


t0s='t0s'
m0s='m0s'
betas='betas'
rnips='rnips'
shotsfile='shotsfile'
anglefile='anglefile'
model = 'constv'

velinv = 'modelinv'
vspline = 'vspline'

for i in range(1):
	velinv = 'modelinv_%d' % i
	vspline = 'vspline_%d' % i
	Flow([velinv,vspline],[model,t0s,m0s,rnips,betas,sv,interpolatedDataCube,shotsfile],
	    '''
	    stereoniptomo1 t0s=${SOURCES[1]} m0s=${SOURCES[2]} rnips=${SOURCES[3]} betas=${SOURCES[4]} sv=${SOURCES[5]} vspline=${TARGETS[1]} data=${SOURCES[6]} shotsfile=${SOURCES[7]} v0=1.508 nit=%d c0=0.75 temp0=1.5 
	    ''' % (nit))

	model = velinv
	sv = vspline

# NIP model setup after velocity model inversion,
# ray-tracing from acquisition surface to NIP sources
Flow(['ray2','nipangles2'],[velinv,shotsfile,anglefile,t0s],
        '''
        nipmodsetup shotsfile=${SOURCES[1]} anglefile=${SOURCES[2]} t0s=${SOURCES[3]} nipangles=${TARGETS[1]} | dd type=complex
        ''')

Flow('result','ray2','sfdd type=float')

# Plot inverted velocity model with NIP sources
Plot('velocityModel',velinv,
	'''
	grey color=j scalebar=y barreverse=y bias=1.508 title="Inverted velocity model" barlabel="Velocity" barunit="Km/s" min2=1 max2=5
	''')

Plot('inverted-nipsources','ray2','sfgraph scalebar=y symbol=+ transp=y yreverse=y max1=3 min1=0 min2=1 max2=5 wanttitle=n wantaxis=n plotcol=7 symbolsz=10')

Plot('inverted-interfaces',['velocityModel','inverted-nipsources'],'Overlay')

# Plot original velocity model
Plot('mod1',trueModel,
	'''
	put label1=Depth unit1=Km label2=Position unit2=Km |
	grey color=j scalebar=y barreverse=y bias=1.508 title="Original velocity model" barlabel="Velocity" barunit="Km/s" min1=0 max1=3 min2=1 max2=5
	''')

Plot('mod1-img',['mod1','inverted-nipsources'],'Overlay')

# Plot result: Inverted and original models side by side
Result('inverted-original',['inverted-interfaces','mod1-img'],'SideBySideIso')

Plot('reference',None,'math output="1.5" n1=300 d1=0.01 o1=0 | graph max1=3 min1=0 max2=2.5 min2=1.4 plotcol=3 yreverse=y transp=y wantaxis=n dash=1')

Plot('velnodes',vspline,'put o1=0 d1=0.5 | graph max1=3 yreverse=y min2=1.4 max2=2.5 min1=0 symbol=+ symbolsz=10 plotcol=2 transp=y wantaxis=n')

Plot('trueProfile',trueModel,'window n2=1 f2=0 | graph yreverse=y min1=0 max1=3 max2=2.5 min2=1.4 transp=y')

Plot('invProfile',velinv,'window n2=1 f2=0 | graph yreverse=y min1=0 max1=3 max2=2.5 min2=1.4 plotcol=1 wantaxis=n transp=y')

Result('profile',['reference','trueProfile','velnodes','invProfile'],'Overlay')

End()
